### PR TITLE
Clean up opam_build and dune_build to use project_build

### PR DESCRIPTION
**Pull request by punchagan**
Simplify installation of packages using opam install instead of git clones and
dune builds.

### CODE REVIEW

**Comment by art-w** [comment]
Thanks, it looks great! Would you like to merge your changes? I personally think your repo should become the reference for these scripts, and that mine should be abandoned :P

**Comment by punchagan** [comment]
I'm using the PR branch directly to run the benchmarks, and it does look weird that the benchmarks being used are in some weird branch in some random repo. I think, we can 

1) Merge the PR
2) Make @tarides the owner of your repository, so that it becomes the reference, instead of our personal repositories.

**Comment by art-w** [comment]
Agree!

**Comment by punchagan** [comment]
Thank you! I'll update the configuration to use this repository.

**Pull request merged**
